### ISSUE TITLE
always "Print Time Left: a minute"

### ISSUE THREAD

**Issue by screwyluie** [sysadminsh/OctoPrint-M73ETAOverride#1]
just installed it on octopi through the plugin manager and this is a 10hr print but the whole time it's been: Print Time Left: a minute
The display on the Prusa works fine

OctoPrint 1.3.9 running on OctoPi 0.14.0

Slic3rPE 1.41.0

**Comment by tbergman88** [comment]
I had the same experience, installed normally but does not seem to work. Does not show the proper remaining time in Octoprint. Prusa display works fine.

**Comment by psy0rz** [comment]
same here..here it seems to just display regular octoprint ETA.

was a octoprint restart needed perhaps?

**Comment by njcrawford** [comment]
Same here. Using Slic3r PE 1.40.0 and OctoPrint 1.9.3. I found that the plugin didn't start working until I restarted OctoPrint, but now it always says "a minute" remaining.

I'm not sure if this is related or not, but I have custom profiles setup for my printers. The only changes from the base profiles are the printer host IP and API key.

Also possibly of note, it doesn't seem like there are any M73 messages in the generated gcode. Is it an option that needs to be turned on in Slic3r PE?

**Comment by njcrawford** [comment]
Nevermind... as soon as I posted that, I went and checked the base MK3 profile, and sure enough, there's an option called "Support remaining times" under General, Firmware. Enabling that option causes M73 message to be added into the gcode. Can't test it with OctoPrint at the moment as both printers are busy, but I'm guessing this was the issue.

**Comment by screwyluie** [comment]
well that makes sense, mine wasn't on either... I'll test it in a bit but I'm sure that'll fix it

**Comment by njcrawford** [comment]
I'd say that was it. Just restarted OctoPrint on the MK3 and enabled "Support remaining times" in Slic3r PE, now OctoPrint is picking up on the time remaining and it's showing up on the MK3's display as well. Guess I need to keep up on my printer profiles as the base profiles change!

**Comment by screwyluie** [comment]
I tried it and it didn't work but I didn't restart octoprint, I'll try that before the next print

**Comment by screwyluie** [comment]
ok yeah a restart of octoprint worked, time left is now correctly shown. Thanks for the help.
